challenge_exit
kfichter/plasma-battleship pull request #3
Opened 2018-07-14 21:50 UTC by parthgargava

2018-07-15 16:34 UTC, smartcontracts requested changes
Requesting a few small changes.

2018-07-15 16:34 UTC, kfichter commented on contracts/RootChain.sol
> +        var txHash = keccak256(_encodedSpendingTx);
Let's replace `var` with the corresponding type (e.x. `bytes txHash`)

2018-07-15 16:34 UTC, kfichter commented on contracts/RootChain.sol
> +        var merkleHash = keccak256(txHash, _spendingTxSignatures);
Let's get rid of `_spendingTxSignatures` here entirely and instead use `keccak256(txHash)`.

2018-07-15 16:34 UTC, kfichter commented on contracts/RootChain.sol
> +        uint256 _txindex  = (_spendingTxPosition % 1000000000) / 10000;
We can make use of `PlasmaCore` here instead:
`uint256 _txindex = getTxIndex(_spendingTxPosition)`

Likewise for `root`.

2018-07-15 16:34 UTC, kfichter commented on contracts/RootChain.sol
> +        bytes32 root = plasmaChain[_spendingTxPosition / 1000000000].root; //need to make plasma chain/child chain
I think it'd be cleaner to separate the `blknum` variable here instead of doing it in one line.

2018-07-16 14:34 UTC, parthgargava reviewed
Ok, the changes make sense

2018-07-16 23:01 UTC, closed without merging